version: 2
build:
    os: ubuntu-24.04
    tools:
        python: "3.13"
    create_environment:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
        - uv venv
    install:
        - uv pip install .[doc,tcoda,de]
    build:
        html:
            - uv run sphinx-build -T -W -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py

submodules:
    include: all
