version: 2
build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    commands:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
        - uv sync --extra docs --frozen
        - uv run -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
    jobs:
        pre_build:
            - python -c "import pertpy"
            - pip freeze
sphinx:
    configuration: docs/conf.py
    fail_on_warning: false
python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - doc
              - coda
              - de
              - validator

submodules:
    include: all
